apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qvpegzy9b-python 
  janus-idp.io/tekton: qvpegzy9b-python
  backstage.io/kubernetes-id: qvpegzy9b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qvpegzy9b-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml